### ISSUE TITLE
LoginFlow restructure

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#343]
We currently have our `AccountsBloc` that is added to a provider and thus accessible throughout the app.
My idea is to let it also handle the loginflow by making it instantiate a `LoginBloc` and handle it's lifecycle.
This has the big advantage that we can access the LoginBloc (if instantiated) wherever we have an AccountsBloc.

My intention was to separate the `UrlEntryScreen` and the `WebViewScreen` and having access to the LoginBloc is crucial for this.
We could just pass it as a parameter or instantiate a new Provider making the LoginBloc only accessible for children of the `UrlEntryScreen`.

In #338 I wanted to make routing automatic so once a user is logged in the router would get notified and just redirect us to the homescreen (wich would show the homescreen for the currently active app and account).
Sadly once we wanted to login a second user the redirection logic intercepted our routing to the LoginScreen and again redirected us to the HomeScreen (if we knew that a new login was instantiated we could also decide based on that knowledge).

Lastly we could also move all of
https://github.com/provokateurin/nextcloud-neon/blob/d47461f4456279a231b6cbfde049c2110a288053/packages/neon/neon/lib/src/pages/login.dart#L60-L95

into the AccountsBloc as it is a perfect candidate of business logic that does not need to be in the Widget. As for the error case we could use the streams onError callback to handle the snackbars in the UI.

---

I'm not that sure if it does make sense to move all routing decisions to the go_router redirection feature as I'd need to see how that would turn out but I think that moving LoginBloc into the AccountsBloc would be a good cleanup of some UI code.

Finally we should also have #283 in mind as it's also LoginFlow related.

**Comment by provokateurin** [comment]
Sounds about right, would you mind opening a PR for that?

https://github.com/provokateurin/nextcloud-neon/issues/284 should also be considered because it makes everything a little more complicated. For the login flow we first get the url and need to check the server connection before initializing the flow, but for qr code we get all the information at once and need to check the server connection.
My idea was to have a `ServerConnectionPage` that would show some loading spinners or checkmarks or exclamation marks based on the connection. The four categories for that would be status (is it reachable), server version (compatibility), maintenance mode (not really relevant for qr login, but login flow won't work) and the credentials (basically what https://github.com/provokateurin/nextcloud-neon/blob/d47461f4456279a231b6cbfde049c2110a288053/packages/neon/neon/lib/src/models/account.dart#L10 is doing, but showing an error when a 401 is returned).

I think this is getting a little bit complicated, so maybe we should start with drawing a diagram that shows the different cases (login method and parameters like re-login or adding second account) and how they interact with which blocs.

**Comment by Leptopoda** [comment]
> I think this is getting a little bit complicated, so maybe we should start with drawing a diagram that shows the different cases (login method and parameters like re-login or adding second account) and how they interact with which blocs.

good idea. Could you do that as you already know what's needed for the qr case?

> Sounds about right, would you mind opening a PR for that?

I'll happily do that but it might slip to after the 11-06-2023.

> My idea was to have a `ServerConnectionPage`

I'm not sure I like the UX/UI flow of that but it would certainly be easier to implement with the mentioned changes.

**Comment by provokateurin** [comment]
Currently there is almost no documentation in the whole project, but the diagram could be some start for it.

**Comment by provokateurin** [comment]
I will try to implement this now
