### ISSUE TITLE
Support for Nextcloud Server v27

### ISSUE THREAD

**Issue by AdmerStroh** [provokateurin/nextcloud-neon#391]
Hello,
I want to kindly ask, if it would be possible to support Nextcloud 27. 
https://github.com/adil192/saber/issues/717

Keep all the good work up and thank you in advance :)

**Comment by ceskyDJ** [comment]
Are there any Nextcloud-specific problems with supporting multiple versions? I think it should be a deal breaker for apps, when their authors see this problem. It'd cause problems for many users, because they often can't upgrade Nextcloud to the new version (for commercial instances) or can't do it for some reason (e.g. incompatibility of important apps). So, I think, this should be resolved in some way. Maybe you can just switch communication objects (I don't know your code, but if you designed using DI, it shouldn't be a big problem) for now and come up with a better solution in the future. What do you think?

**Comment by provokateurin** [comment]
The problem with supporting multiple versions is because of breaking API changes. We have some plans on how to deal with this but there will also be some changes in the future on the Nextcloud side that will make APIs much more stable

**Comment by ceskyDJ** [comment]
I see, thanks for your explanation. So, what about my proposal? Is it hard to implement due to the design of your library? Do you know something more about the "stabilizing" of the Nextcloud API (especially when it is planned to be released)?

**Comment by provokateurin** [comment]
I also work at Nextcloud and will be responsible for creating a versioning/compatibility strategy. I haven't written down anything concrete yet and it will still be some time until I pickup that task, but we aim to provide API stability for about 2-3 years before introducing breaking changes.
If you have anything special in mind please let me know, I will consider it :)

**Comment by ceskyDJ** [comment]
Thanks for providing more information. I did a quick code lookup and finally understood the problem (at least I believe it). You depend on other libraries with break changes, so you can't do anything with this problem. I thought you set up your own wrapper of the Nextcloud API (so WebDAV, CalDAV, CardDAV, etc.), so you would be able to have more wrappers' implementations and just switch between them by the Nextcloud server version.

**Comment by provokateurin** [comment]
No, we don't depend on other libraries for the Nextcloud API. All the code for that is in this repository. As I said, we have some plans to support multiple versions in the future (probably starting with 27 or 28)
