### ISSUE TITLE
Genrate libraries per spec

### ISSUE THREAD

**Issue by Leptopoda** [provokateurin/nextcloud-neon#419]
Far various reasons we should generate libs per spec:
- news.openapi.dart
- notes.openapi.dart
- $app.openapi.dart

depends on #418

**Comment by provokateurin** [comment]
Important for https://github.com/provokateurin/nextcloud-neon/issues/417:

One problem with this will be that the openapi-extractor correctly merges all the capability types when generating the merged spec. We need to deal with that too, otherwise the capabilities become an untyped object.

I'd say we also generate the merged spec and then extract the merged capabilities type from there and inject it into the core spec. That way we don't need to rewrite the capabilities merging again.

**Comment by provokateurin** [comment]
Depending on which of these issues is addressed first, the task of implementing the merging will go to the one that is still open.

**Comment by Leptopoda** [comment]
Should we do this one first so we can find and fix potential issues with dynamite before doing the jump to the automatic specs?

**Comment by provokateurin** [comment]
Yep, let's do that
