### ISSUE TITLE
 support self signed certificates for custom nextcloud server

### ISSUE THREAD

**Issue by AdmerStroh** [provokateurin/nextcloud-neon#444]
I have a custom nextcloud server with a self signed certificate. Connecting via http works, but when I try https the login fails.
I already imported my custom certificate into the system, therefore visiting the nextcloud interface via https works.

To reproduce:
1. try to login to a nextcloud instance with self signed certificate via https
2. login fails

Expected behavior:
nextcloud-neon should respect certificates installed system-wide and allow to log into nextcloud instances with self signed ssl certificates

See https://github.com/adil192/saber/issues/773

**Comment by provokateurin** [comment]
We don't want to support this by default because it is insecure. If you still wish to have self signed certificates working you need to override the http client and do something like https://github.com/dart-lang/http/issues/458. @adil192 please implement this in saber if you want to support it, it's not related to the nextcloud lib

**Comment by adil192** [comment]
@provokateurin In the future, when I receive a Nextcloud-related issue, would you prefer I:
- @mention you on the original issue
- Ask the issuer to refile the issue on this repo
- I make an issue on this repo and link the original issue
- None/something else

**Comment by provokateurin** [comment]
I think pinging is the best, I can probably quickly judge if the problem is on our side or not.
