### ISSUE TITLE
Quick actions not working all the time

### ISSUE THREAD

**Issue by provokateurin** [provokateurin/nextcloud-neon#492]
Sometimes when using the quick actions the wrong app opens. This only seems to happen when you have selected the initial app to be automatic. Also doesn't happen all the time, so it's pretty likely a race condition. If the app is already open in the background it works all the time.

**Comment by Leptopoda** [comment]
I have a 100% failure rate on a slower device.
Even with another app like `news` set as the initial one.

I haven't had time to investigate further but I suspect that loading the account is slow thus:
https://github.com/provokateurin/nextcloud-neon/blob/594ecb2c0bdb17a3585e91e198ce515fb0824f2e/packages/neon/neon/lib/src/app.dart#L229-L232

fails because activeAccount isn't yet initialized with a value.

**Comment by provokateurin** [comment]
Can confirm, severly downclocking my phone also leads to 100% broken rate

**Comment by provokateurin** [comment]
The account and app is correctly loaded, but overwritten afterwards by the default app that is loaded
